apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ion-c5.fullname" . }}-config
  labels:
    {{- include "ion-c5.labels" . | nindent 4 }}
data:
  config.ini: |
    {{- include "ion-c5.configIni" . | nindent 4 }}
